server:
  port: 8081 # 端口

spring:
  application:
    name: multi-datasource-service  # 应用名

  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配配项，对应 DynamicDataSourceProperties 类
    dynamic:
      primary: order-ds # 设置默认的数据源或者数据源组，默认值即为 master
      datasource:
        # 订单 order 数据源配置
        order-ds:
          url: jdbc:mysql://192.168.199.112:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
        # 账户 pay 数据源配置
        account-ds:
          url: jdbc:mysql://192.168.199.112:3306/seata_account?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
        # 商品 product 数据源配置
        product-ds:
          url: jdbc:mysql://192.168.199.112:3306/seata_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
      seata: true # 是否启动对 Seata 的集成
#  cloud:
#    alibaba:
#      seata:
#        enabled: true
#        enable-auto-data-source-proxy: true #开启使用seata对数据源进行代理
#        #在nacos上查找seata的配置信息
#        tx-service-group: multi-datasource-service-group
#        registry:
#          type:
#          nacos:
#            application: seata-server
#            server-addr: 192.168.199.112:8848
#            username: nacos
#            password: nacos
#        config:
#          type: nacos
#          nacos:
#            server-addr: 192.168.199.112:8848
#            group: seata_demo #默认上传的组名
#            username: nacos
#            password: nacos
#            namespace: d197f572-96bf-400f-b21e-0f38a2198ef1
#        service:
#          vgroup-mapping:
#            multi-datasource-service-group: default
#          disable-global-transaction: false
#        client:
#          rm:
#            report-success-enable: false



# Seata 配置项，对应 SeataProperties 类
seata:
  application-id: seata-server # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: multi-datasource-service-group # Seata 事务组编号，用于 TC 集群名
  # 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      multi-datasource-service-group: default
    # 分组和 Seata 服务的映射
    grouplist:
      default: 192.168.199.112:8091
  config:
    type: nacos
    nacos:
      server-addr: 192.168.199.112:8848
      group: seata_demo
      namespace: d197f572-96bf-400f-b21e-0f38a2198ef1
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.199.112:8848
      group: seata_demo
      namespace: d197f572-96bf-400f-b21e-0f38a2198ef1
      username: nacos
      password: nacos
